---
title: "Project Stuff"
author: "Owen Wright"
date: "11/15/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(igraph)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(visNetwork)
library(networkD3)
```

#activities imports, adding names as a column to aid in our kudos network
```{r}
Elliot_run<-read_csv("Elliot/activities.csv")%>% #Elliot's data messing
  filter(type=="Run",
         date>"2018-6-01")%>%
  mutate(miles=distance/1609,
         minutes=elapsed_time/60,
         pace=minutes/miles)%>%
  filter(pace<10)%>%
  select(-type, -gear, -commute)%>%
  mutate(person="ell",
         name="Elliot",
         count=131)

Justin_run<-read_csv("Fursnatch/activities.csv")%>% #Justin's data messing
  filter(type=="Run",
         date>"2018-6-01")%>%
  mutate(miles=distance/1609,
         minutes=elapsed_time/60,
         pace=minutes/miles)%>%
  filter(pace<10)%>%
  select(-type, -gear, -commute)%>%
  mutate(person="3",
         name="Justin",
         count=936)
Mowgli_run<-read_csv("Mowgli/activities.csv")%>% 
  filter(type=="Run",
         date>"2018-6-01")%>%
  mutate(miles=distance/1609,
         minutes=elapsed_time/60,
         pace=minutes/miles)%>%
  filter(pace<10)%>%
  select(-type, -gear, -commute)%>%
  mutate(person="4",
         name="Mowgli",
         count=335)
Birdo_run<-read_csv("Birdo/activities.csv")%>%
  filter(type=="Run",
         date>"2018-6-01")%>%
  mutate(miles=distance/1609,
         minutes=elapsed_time/60,
         pace=minutes/miles)%>%
  filter(pace<10)%>%
  select(-type, -gear, -commute)%>%
  mutate(person="birdo",
         name="Birdo",
         count=642)

Jackson <- read_csv("Jackson/activities.csv")
Jackson_run<-Jackson%>%
  filter(type=="Run",
         date>"2018-6-01")%>%
  mutate(miles=distance/1609,
         minutes=elapsed_time/60,
         pace=minutes/miles)%>%
  filter(pace<10)%>%
  select(-type,-gear, -commute)%>%
  mutate(person="2",
         name="Jackson",
         count=531)
Finn_run<-read_csv("Finn/Finn/activities.csv")%>%
  filter(type=="Run",
         date>"2018-6-01")%>%
  mutate(miles=distance/1609,
         minutes=elapsed_time/60,
         pace=minutes/miles)%>%
  filter(pace<10)%>%
  select(-type,-gear, -commute)%>%
  mutate(person="1",
         name="Finn",
         count=370)
Plumb_run<-read_csv("Plumb/activities.csv")%>%
  filter(type=="Run",
         date>"2018-6-01")%>%
  mutate(miles=distance/1609,
         minutes=elapsed_time/60,
         pace=minutes/miles)%>%
  filter(pace<10)%>%
  select(-type,-gear, -commute)%>%
  mutate(person="5",
         name="Plumb",
         count=761)

all_activities<-Elliot_run%>%
  rbind(Justin_run, Birdo_run, Mowgli_run, Jackson_run, Finn_run, Plumb_run)%>%
  select(-filename)


## WORD CLOUD http://www.sthda.com/english/wiki/text-mining-and-word-cloud-fundamentals-in-r-5-simple-steps-you-should-know
word <- function(runner, runner_n, runner_des){
for(i in 1:count(runner)[[1]]){
  write(runner_n[i], file="out.txt", append=TRUE)
  write(runner_des[i],file="out.txt",append=TRUE)
}

filePath <- "out.txt"
text <- readLines(filePath)
docs <- Corpus(VectorSource(text))
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 5,
          max.words=200, random.order=FALSE, rot.per=0.25, 
          colors=brewer.pal(8, "Dark2"))
}

word(all_activities, all_activities$name, all_activities$description)

```


#Kudos imports, adding column with name to create network
```{r}
Finn_kudos<- read_csv("Finn/Finn/kudos.csv")%>%
  mutate(giver="1")
Justin_kudos<- read_csv("Fursnatch/kudos.csv")%>%
  mutate(giver="3")
Jackson_kudos<- read_csv("Jackson/kudos.csv")%>%
  mutate(giver="2")
Mowgli_kudos<- read_csv("Mowgli/kudos.csv")%>%
  mutate(giver="4")
Plumb_kudos<- read_csv("Plumb/kudos.csv")%>%
  mutate(giver="5")
all_kudos<-Finn_kudos%>%
  rbind(Justin_kudos, Jackson_kudos, Mowgli_kudos, Plumb_kudos)
#merging all activities and kudos 
kudos_match<-all_kudos%>%
  inner_join(all_activities, by="id")%>%
  select(giver, person, elapsed_time, distance, miles, minutes, pace, name, description, count)
#then we can mess around with grouping to create our network
network<-all_kudos%>%
  inner_join(all_activities, by="id")%>%
  select(giver, person, elapsed_time, distance, miles, minutes, pace, name, description, count)%>%
  group_by(giver, person)%>%
  summarise(number=n())%>%
  spread(person, number, drop=FALSE, fill=0)%>%
  ungroup()%>%
  select(-birdo, -ell,-giver)
net_matrix<-as.matrix(network)

g2<-from_adjacency(net_matrix)
g2


g<-graph.adjacency(net_matrix, mode="direct", weighted=NULL)

visnet<-kudos_match%>%
  filter(person!="birdo" & person!="ell")%>%
  group_by(giver, person)%>%
  mutate(number=n())%>%
  ungroup()%>%
  mutate(prop=number/count)%>%
  group_by(giver, person)%>%
  summarise(percentage=100*mean(prop))
visnet
  
colnames(visnet)[colnames(visnet)=="giver"] <- "from"
colnames(visnet)[colnames(visnet)=="person"] <- "to"
colnames(visnet)[colnames(visnet)=="percentage"] <- "weight"
visnet$value = visnet$weight
visnet$color = c("red","red","red","red","blue","blue","blue","blue","green","green","green","green","orange","orange","orange","orange","pink","pink","pink","pink")
visnet$length = c(100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100)
visnet$dashes = c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE)

nodes$x <- c(1, 0, -1, 0, 1.5)*100
nodes$y <- c(0, 1, 0, -1, 1.5)*100
nodes<-tibble(id=1:5,
       label=c("finn", "jack", "justin", "mowg", "plumb"))  

visNetwork(nodes, visnet) %>%
  visEdges(smooth=TRUE) %>%
    visNodes(fixed=FALSE, shape = "circle", color = c(highlight = "purple"))



```

```{r}
df <- function(giver, taker){
  giver %>%
    inner_join(taker, by="id") %>%
    count()
  
}
net_matrix


```

```{r}

pace_zones <- all_activities%>%
  filter(pace < 10) %>%
  group_by(person)%>%
  summarise(avg_pace=mean(pace),
            variability=sd(pace),
            tempo=sum(pace<6.01&pace>5.51),
            fast=sum(pace<5.51),
            medium=sum(pace>6.01&pace<6.31),
            sixthirty=sum(pace>6.31&pace<7.01),
            easy=sum(pace>7.01&pace<8.01),
            real_easy=sum(pace>8.01),
            num_long=sum(miles>14),
            pct_long=num_long/n(),
            avg_distance=mean(miles),
            total=sum(miles),
            num = n())


times[1] <- 27.520
times[2] <- 27.15
times[3] <- 25.4
times[4] <- 27.33
times[5] <- 25.67
times[6] <- 28.91
times[7] <- 25.65
times[8] <- 25.11


times2 <- 1:8
times2[1] <- 29.020
times2[2] <- 27.7
times2[3] <- 26.3
times2[4] <- 27.133
times2[5] <- 26.25
times2[6] <- 26.25
times2[7] <- 26.88
times2[8] <- 26.48
#3 = justin, 4 = mowgli, 1 = finn, 2 = jackson, 5 = plumb


PR <- tibble(name = c("Finn","Jackson","Justin","Mowgli","Plumb", "Birdo", "Elliot", "Bill"), best_2018 = times, best_2017 = times2)
PR <- PR %>%
  mutate(
    improvement = best_2017 -best_2018
  )

PR
ggplot(data = all_activities, mapping = aes(x = pace)) +
  geom_density(aes(fill=name))
#If we do Shiny we could have the ability to click and unclick names since there is overlapping.


ggplot(data = pace_zones, mapping = aes(x=person)) +
  geom_point(aes(y= avg_pace))

ggplot(pace_zones, aes(x = person, y = num, fill = easy)) + 
  geom_bar(stat = "identity")

pr_zones <- left_join(pace_zones, PR)
pr_zones

ggplot(pr_zones) +
  geom_point(aes(x=avg_pace, y = best_time))

ggplot(pr_zones) +
  geom_point(aes(x=total, y = best_time)) 

ggplot()+
  geom_smooth(aes(x = Jackson_run$date, y=Jackson_run$pace, color = "red")) +
  geom_smooth(aes(x = Justin_run$date, y=Justin_run$pace, color = "blue")) +
geom_smooth(aes(x = Elliot_run$date, y=Elliot_run$pace, color="green")) +
  geom_smooth(aes(x = Finn_run$date, y=Finn_run$pace, color = "purple")) +
  geom_smooth(aes(x = Mowgli_run$date, y=Mowgli_run$pace)) 
  


all_activities%>%
  group_by(name)%>%
  ggplot(aes(x=date, y=pace, color=name))+
  geom_smooth(se=FALSE)


left_join(all_activities, )
  
plot(Jackson_run$miles ~ Jackson_run$date, xaxt = "n", type = "l") 
```
#turning what qualifies as "fast" into a statistic thats athlete specific?
